name: GitHub CI
on: 
  push:
    branches: [ master ]
    tags:
      - '**'
  workflow_dispatch:
  pull_request:

concurrency: 
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  freebsd_build:
    runs-on: ubuntu-latest
    name: FreeBSD Build
    steps:
    - name: Checkout base
      uses: actions/checkout@v4
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
    - name: Build
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: pkg install -y curl bash git nodejs npm
        run: cd /root/workdir && chmod +x scripts/build.freebsd.release.sh && bash scripts/build.freebsd.release.sh
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: subconverter/
    - name: Package Release
      if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') }}
      run: tar czf subconverter_freebsd64.tar.gz subconverter
    - name: Draft Release
      if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v2
      with:
        files: subconverter_freebsd64.tar.gz
        draft: true